### ISSUE TITLE
[疑问] 请教一下relay+tls的ss要如何配置

### ISSUE THREAD

**Issue by ztywyj** [segfault-bilibili/ShadowsocksGostPlugin#2]
落地机有ss服务端和relay+tls的隧道，在linux上我通过写以下的配置文件可以用开放的33333端口正常连接：
{
    "Debug": true,
    "Retries": 0,
    "ServeNodes": [
        ":33333"
    ],
    "ChainNodes": [
        "ss://aes-256-gcm:passwd@:22222"
    ],
    "Routes": [
        {
            "Retries": 0,
            "ServeNodes": [
                "tcp://:22222",
                "udp://:22222"
            ],
            "ChainNodes": [
                "relay+tls://example.com:11111?secure=true"
            ]
        }
    ]
}
但android上不知道如何设置，试过把ServeNodes清空，用 -C config.json，但无法正常连接

**Comment by segfault-bilibili** [comment]
看了一下是配置没加载，我这边刚刚改了一下：https://github.com/segfault-bilibili/ShadowsocksGostPlugin/releases/tag/3.0.0-rc.0-gui

**Comment by segfault-bilibili** [comment]
另外可能没必要加`ServeNodes`

**Comment by ztywyj** [comment]
感谢大佬回复，不过改成yaml不知道怎么写了...之前我的方案，也就是relay+tls隧道中转ss协议的方式，在各平台的gost客户端上都不太好配置，不光是ssgost插件的问题，所以还是改成了直接ss+tls的方案，目前用起来没有什么问题

**Comment by segfault-bilibili** [comment]
JSON也能用

**Comment by segfault-bilibili** [comment]
有空你可以再试一下gost，没问题就close issue

**Comment by ztywyj** [comment]
你好，我又试了一下，不用config的情况下，我直接添加一条 -F ss+tls://aes-256-gcm:password@#SS_HOST:#SS_PORT?secure=true，然后ss地址和端口填写正确，密码空，加密none，是可以成功运行的，但用config的情况下就不行，我的写法如下
```json
{
    "Debug": true,
    "Retries": 0,
    "ServeNodes": [
        
    ],
    "ChainNodes": [
        "ss+tls://aes-256-gcm:password@#SS_HOST:#SS_PORT?secure=true"
    ]
}
```
然后加了一条 -C config.yaml，运行是无法联通的。
我也尝试过把-L里的东西写到ServeNodes
```json
{
    "Debug": true,
    "Retries": 0,
    "ServeNodes": [
        "ss://none@#SS_LOCAL_HOST:#SS_LOCAL_PORT"
    ],
    "ChainNodes": [
        "ss+tls://aes-256-gcm:password@#SS_HOST:#SS_PORT?secure=true"
    ]
}
```
运行还是无法联通，我也试过再把原本的-L指令删除，只留-C config.yaml，也不行
再就是把#SS_HOST和#SS_PORT直接写为正确的地址端口，也是不行
请帮我看下是我哪边写法不对还是什么问题

**Comment by segfault-bilibili** [comment]
目前配置文件里的`#SS_HOST`和`#SS_PORT`不会被替换，看样子我这边还需要改。

另外文件名可以是config.json，下面有添加按钮。

**Comment by ztywyj** [comment]
好的，之前没注意下面可以添加文件，我添加了一个config.json，把`#SS_HOST`和`#SS_PORT`直接替换成了地址和端口，还是不行，ServeNodes为空或者填入`"ss://none@#SS_LOCAL_HOST:#SS_LOCAL_PORT"`也不行

**Comment by odesky** [comment]
您好,大神们.
     我的情况也有点相同,是以SS-RUST落地.客户端与服务端只用GOST V3作为隧道使用. GOST不作为SS的服务端.
     那请问我该如何设定ShadowsocksGostPlugin?

SS-RUST (WIN10)客户端配置为如下:
```
 服务器地址: localhost
服务器端口: 22312
密码: *******
加密: aes-128-gcm

```

以下是我的 (WIN10)客户端GOST连接配置.
```
services:
- name: service-22312-tcp
  addr: :22312
  handler: 
    type: tcp
    chain: chain-2
  listener: 
    type: tcp
- name: service-22312-udp
  addr: :22312
  handler: 
    type: udp
    chain: chain-2
  listener: 
    type: udp


chains: 
- name: chain-2
  hops: 
  - name: hop-2
    nodes: 
    - name: node-2
      addr: "www.abc.com:20088"
      connector: 
        type: relay
      dialer: 
        type: tls
        tls: 
         caFile: "ca.pem"
          secure: true
          serverName: "www.abc.com"
```
